### ISSUE TITLE
Use without build systems?

### ISSUE THREAD

**Issue by gabrielgggg** [grimme-lab/nlopt-f#10]
Hello!
Say I'm using a simple Makefile or other very simple "manual" command to compile my code. What are the ``-I`` and ``-L`` I need?
Using

``-I/usr/local/include/nlopt-f/GNU-9.3.0 -L/usr/local/lib -lnlopt-f -lnlopt -lm``

compiles fine, but then when I try to run the resulting executable I get

``./test: symbol lookup error: ./test: undefined symbol: nlopt_algorithm_from_string``

I can run the executable file if I set LD_LIBRARY_PATH before execution, to include ``/usr/local/lib``.

I installed with cmake/ninja. Is it possible to configure it easily to install the ``.a`` and ``.mod``-s and so on in locations that are by default in the ``LD_LIBRARY_PATH`` and include path, or is it a problem with my  system (Ubuntu LTS)?

Thank you!

**Comment by awvwgk** [comment]
If you are using a simple Makefile, why not give [fpm](https://github.com/fortran-lang/fpm) a try?

**Comment by gabrielgggg** [comment]
I looked briefly into it but it seemed a bit opaque (that is, I am too much of a brainlet to "get it"). I want to compile the same code on my machine with ifort, some other time I use the cray compiler on an ARM cluster, some of the code is MPI, some is openmp, some both. I didn't see how fpm chooses performance flags and so on. My project usually has 1-2 modules and 1 program, all Fortran, so not much of a "build".
