### ISSUE TITLE
Error for private component of 'nlopt_func'

### ISSUE THREAD

**Issue by huijunchen9260** [grimme-lab/nlopt-f#26]
Dear all:

Not sure whether this is a good place to post this issue, yet I cannot any helpful documentation about how to nlopt-f binding.

I am now learning how to use this fortran binding to use nlopt to solve my model. My current progress is [here](https://github.com/huijunchen9260/try-for-nlopt), and now when I compile this project using `fpm run`, I got the following error, and somehow I just don't know how to solve it:

```fortran
:!fpm run --flag="-O3"
fpm: Entering directory '/home/huijunchen/mnt/home/huijunchen/Documents/Google_Drive/Ohio_related/PhD_Fourth_Year/research/nlopt_test/neoclassical_
nlopt_ver2'
 [   0%]   neoclassical_nlopt_ver2.f90
 [  25%]   neoclassical_nlopt_ver2.f90  done.

./src/neoclassical_nlopt_ver2.f90:133:36:

  133 |         call opt%set_max_objective(nlopt_func(kupObj, evvec))
      |                                    1
Error: Component ‘f’ at (1) is a PRIVATE component of ‘nlopt_func’
<ERROR> Compilation failed for object " src_neoclassical_nlopt_ver2.f90.o "
<ERROR>stopping due to failed compilation
STOP 1
```

Thank you so much in advance for your help!

HJ

**Comment by ivan-pi** [comment]
Hi HJ,

the issue on line 133 looks related to #13, i.e. the lifetime of the object created by `nlopt_func` is only valid inside the call to `set_max_objective` and not until the optimize step.

From looking at your repository, it seems you've already found the "right" way to do it, using the `associate` command:

```fortran
        associate( f => nlopt_func(kupObj, vdata) )
            call opt%set_xtol_rel(tol)
            call opt%set_max_objective(f)
            call opt%optimize(guess, fmax, stat)
        end associate
```

The other way I believe is to create a `nlopt_func` variable explicitly:

```
type(nlopt_func) :: f
f = nlopt_func(kupObj,vdata)

call opt%set_xtol_rel(tol)
call opt%set_max_objective(f)
call opt%optimize(guess, fmax, stat)
```

Does this help?

**Comment by huijunchen9260** [comment]
Yes! I somehow figured out how to use this interface and being able to use this interface to do the [replication](https://github.com/huijunchen9260/ReplicateLanteri2018_nlopt) of some model.

May I also ask some question on how to use this interface?

Right now I basically treat the nlopt as a interface to do one dimensional optimization, and loop over all necessary times in the caller side, i.e., 

```fortran
 do inde = 1, enum, 1
                epsval = egrid(inde)
                evvec = ev(:, inde)
                conf%evvec = evvec
                call kupTarget(kupstar, evupstar, conf)
enddo 
```
(actual code chuck is [here](https://github.com/huijunchen9260/ReplicateLanteri2018_nlopt/blob/main/src/ReplicateLanteri2018.f90#L141-L146)

where `kupTarget` is the optimization function that contains `nlopt-f` interface, where guess is one dimensional array:
```fortran
        guess = kgrid(knum/2)

        ! call create(opt, algorithm_from_string("LN_SBPLX"), int(knum, 4))

        ! remember that the last number is in int4 but not 8
        call create(opt, algorithm_from_string("LN_SBPLX"), 1) ! I think the number 1 means one dimensional
        call opt%set_lower_bounds(kgrid(1))
        call opt%set_upper_bounds(kgrid(knum))
        associate( f => nlopt_func(kupObj, conf) )
            call opt%set_xtol_rel(tol)
            call opt%set_max_objective(f)
            call opt%optimize(guess, fmax, stat)
        end associate
        call destroy(opt)
```
(actual code chuck is [here](https://github.com/huijunchen9260/ReplicateLanteri2018_nlopt/blob/main/src/ReplicateLanteri2018.f90#L456-L469)

I am wondering is this a good/efficient way to use this interface? Or I just use this as a `enum`-dimensional question and optimize them all together?

Thank you!

HJ

**Comment by awvwgk** [comment]
> Right now I basically treat the nlopt as a interface to do one dimensional optimization, and loop over all necessary times in the caller side

The parameter array passed to the optimizer is always flattend, *i.e.* rank 1. If you are optimizing a rank 2 parameter array you have to pass it as a rank 1 view, *e.g.* by array bound remapping.

> ```fortran
>         call create(opt, algorithm_from_string("LN_SBPLX"), 1) ! I think the number 1 means one dimensional
> ```

The last argument is the number of parameters to optimize, *i.e.* `size(guess)` would be the correct choice here. You should find that the optimization will only change the first element of the array `guess`.

**Comment by huijunchen9260** [comment]
Great! I think that closes most of my questions! Thank you so much with this amazing project 😀😀
